"use strict";
exports.__esModule = true;
exports.circleArea = exports.rhombusArea = exports.parallelogramArea = exports.trapeziumArea = exports.triangleArea = exports.squareArea = exports.rectangleArea = exports.exponent = exports.remainder = exports.divide = exports.multiply = exports.subtract = exports.add = void 0;
var arithmetic_1 = require("./functions/arithmetic");
exports.add = arithmetic_1.add;
exports.subtract = arithmetic_1.subtract;
exports.multiply = arithmetic_1.multiply;
exports.divide = arithmetic_1.divide;
exports.remainder = arithmetic_1.remainder;
exports.exponent = arithmetic_1.exponent;
var _2dShapesArea_1 = require("./functions/2dShapesArea");
exports.rectangleArea = _2dShapesArea_1.rectangleArea;
exports.squareArea = _2dShapesArea_1.squareArea;
exports.triangleArea = _2dShapesArea_1.triangleArea;
exports.trapeziumArea = _2dShapesArea_1.trapeziumArea;
exports.parallelogramArea = _2dShapesArea_1.parallelogramArea;
exports.rhombusArea = _2dShapesArea_1.rhombusArea;
exports.circleArea = _2dShapesArea_1.circleArea;
